quarkus.http.cors.enabled=true
quarkus.http.cors.origins=*
quarkus.smallrye-openapi.info-title=Demo API
quarkus.smallrye-openapi.info-version=1.0.0

quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=postgres
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/pets
quarkus.liquibase.migrate-at-start=true